### PR TITLE
Core: Avoid NPEs on invalid Bazel profiles

### LINKED ISSUE #54: Invalid JSON file causes NullPointerException
## Description

When passing in a valid JSON file that is not a Bazel profile the constructor of `BazelProfile` throws a `NullPointerException`.

### Observed behavior

The constructor tries to access JSON fields that do not exist, leading to a `NullPointerException`.

### Expected behavior

The tool recognizes an invalid profile was passed in and handles it graciously.

### PR DESCRIPTION
**Pull request by saraadams**
Fixes #54

When passing in valid json files that are missing key components of a Bazel profile, an NPE is thrown.
This change checks for the key components before trying to access them and throws an IllegalArgumentException if the components do not exist.

### CODE REVIEW

File: analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java [hunk 1]
```diff
@@ -90,6 +98,10 @@ private BazelProfile(JsonObject profile) {
         .forEach(
             element -> {
               JsonObject object = element.getAsJsonObject();
+              if (!object.has(TraceEventFormatConstants.EVENT_PROCESS_ID)
+                  || !object.has(TraceEventFormatConstants.EVENT_THREAD_ID)) {
+                return;
+              }
               int pid = object.get(TraceEventFormatConstants.EVENT_PROCESS_ID).getAsInt();
```
Comment (ulfjack) [inline analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java:105]: `getAsInt` can also throw, but I suppose that's ok?

**Review by ulfjack — APPROVED** [review]

File: analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java (hunk 1 above)
Comment (saraadams) [reply analyzer/java/com/engflow/bazel/invocation/analyzer/bazelprofile/BazelProfile.java]: I've adjusted the code to use a try/catch block instead.
